name: Uniswap LP Monitor Cron

on:
  schedule:
    - cron: '0 9 * * *'  # Ежедневно в 9:00 UTC. Измените: e.g., '*/30 * * * *' для каждые 30 мин
  workflow_dispatch:  # Для ручного запуска кнопкой в Actions

jobs:
  run-monitor:
    runs-on: ubuntu-latest  # Бесплатный сервер GitHub

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Скачивает ваш репозиторий

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'  # Версия для web3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Устанавливает web3 и requests из вашего файла

    - name: Run script
      run: python uniswap_monitor.py  # Запускает ваш код — он выведет логи и отправит в Telegram

    - name: Log completion
      if: always()  # Показывает "Готово!" даже при ошибке
      run: echo "Cron job completed! Check Telegram for results."
